spring:
  mustache:
    suffix: .html
  profiles:
    include: oauth, real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc

server:
  tomcat:
    basedir: .
    accesslog:
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%X{visitorIp}] [%thread] %-5level %logger{36} – %msg%n"
      enabled: true