spring:
  mustache:
    suffix: .html
---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  mustache:
 #   prefix: classpath:\static\
    cache: false

  resources:
#      static-locations: file:///E:\my\quench-springboot2-webservice\src\main\resources\static

  profiles:
    include: oauth

  session:
    store-type: jdbc

server:
  tomcat:
    basedir: .
    accesslog:
      pattern: %{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b
      enabled: true
